name: make_and_test

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: make tests
